### PR TITLE
Update AWA LWM2M version to 0.2.3

### PR DESCRIPTION
**Pull request by mar3kk**

### CODE REVIEW

**Comment by abhijit-mahajani-imgtec** [comment]
Lets change the BOOTSTRAP for awa_client
BOOTSTRAP=coap://ws-uat.flowworld.com:15683
to Device server

**Comment by mar3kk** [comment]
updated

**Comment by abhijit-mahajani-imgtec** [comment]
Is this valid coaps://deviceserver.flowcloud.systems:15684 for normal public user?
at least ping is not working neither awa_clientd is able to bootstrap

**Comment by mar3kk** [comment]
Yes, it points to publicly available server hosted an AWS. I can connect to
it using awa_clientd without problems. Please note you need valid
certificate or PSK.

2016-08-01 15:27 GMT+02:00 Abhijit A. Mahajani <notifications@github.com>:

**Comment by mar3kk** [comment]
Can anyone approve/verify/merge this PR?

**Comment by nikhil-zinjurde-imgtec** [comment]
Approved & verified

**Pull request merged**
